#!/usr/bin/env bash
# session-orient-learning.sh
# Installed into companion project .claude/hooks/ directories.
# Queries cognee for relevant context and surfaces local learnings at session start.
#
# DO NOT EDIT THIS FILE IN A PROJECT'S hook directory —
# edit the master copy at c:/Projects/Knowledge-Management/scripts/session-orient-learning.sh
# and re-run install-learning-hooks.sh to propagate changes.

# ── Configuration ────────────────────────────────────────────────────────────

COGNEE_DIR="c:/Projects/Knowledge-Management/cognee"
PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
PROJECT_NAME=$(basename "$PROJECT_ROOT" | tr '[:upper:]' '[:lower:]')

# ── Map project to cognee dataset ────────────────────────────────────────────

case "$PROJECT_NAME" in
  movex-rest-api|movex)  DATASET="movex" ;;
  myinvois-service)      DATASET="myinvois" ;;
  sm-portal)             DATASET="sm-portal" ;;
  wms)                   DATASET="wms" ;;
  plm|plmserver)         DATASET="plm" ;;
  difot)                 DATASET="difot" ;;
  reporting-service)     DATASET="reporting" ;;
  *)                     DATASET="org" ;;
esac

# ── Surface local learnings ──────────────────────────────────────────────────

echo ""
echo "=== Knowledge Context for $PROJECT_NAME ==="

LEARNINGS_FILE="$PROJECT_ROOT/ai/memory/learnings.md"
if [ -f "$LEARNINGS_FILE" ]; then
  LEARNING_COUNT=$(grep -c "^### " "$LEARNINGS_FILE" 2>/dev/null || echo "0")
  if [ "$LEARNING_COUNT" -gt 0 ]; then
    echo "  Accumulated learnings: $LEARNING_COUNT entries"
    echo "  Read ai/memory/learnings.md for full details"
    echo ""
    # Show the 3 most recent learnings (titles only)
    echo "  Recent learnings:"
    grep "^### " "$LEARNINGS_FILE" 2>/dev/null | head -3 | sed 's/^/    /'
    echo ""
  fi
fi

# ── Query cognee for project-relevant context ────────────────────────────────

PYTHON="$COGNEE_DIR/.venv/Scripts/python"
if [ -f "$PYTHON" ]; then
  # Query project-specific dataset
  RESULT=$("$PYTHON" "$COGNEE_DIR/query_cli.py" \
    --one-shot "What are the most important warnings, known pitfalls, and recent lessons for $PROJECT_NAME?" \
    --dataset "$DATASET" 2>/dev/null | head -20)

  if [ -n "$RESULT" ] && ! echo "$RESULT" | grep -qi "no results\|error\|not found"; then
    echo "  COGNEE CONTEXT ($DATASET dataset):"
    echo "$RESULT" | sed 's/^/    /'
    echo ""
  fi

  # Also query org dataset for cross-project context (if not already querying org)
  if [ "$DATASET" != "org" ]; then
    ORG_RESULT=$("$PYTHON" "$COGNEE_DIR/query_cli.py" \
      --one-shot "What cross-project warnings or patterns are relevant to $PROJECT_NAME?" \
      --dataset "org" 2>/dev/null | head -10)

    if [ -n "$ORG_RESULT" ] && ! echo "$ORG_RESULT" | grep -qi "no results\|error\|not found"; then
      echo "  CROSS-PROJECT CONTEXT (org dataset):"
      echo "$ORG_RESULT" | sed 's/^/    /'
      echo ""
    fi
  fi
else
  echo "  (cognee not available — run setup in c:/Projects/Knowledge-Management/cognee)"
  echo ""
fi

echo "  Tips:"
echo "    /cognee-query   — targeted knowledge graph lookups"
echo "    /capture-learning — record a lesson after completing work"
echo "========================================"
echo ""
